version: '3'
services:

  db_mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "uwu"
      MYSQL_DATABASE: "videoclub"
      MYSQL_USER: "fuan"
      MYSQL_PASSWORD: "uwu"

  app:
    build: .
    ports:
      - "6969:6969"
    environment:
      - PORT=6969
    depends_on:
      - db_mysql
    command: 
      npm run start